# Site settings
name: Swati Tiwari
title: Swati Tiwari | Salesforce Developer & Consultant
description: Design-minded, detail oriented software engineer passionate about combining beautiful code for the clients.
url: https://brittanychiang.com/
baseurl: ""
email: swatitiwari04@gmail.com
cover: img/og.jpg
logo: img/icons/logo-black.png
resume: resume.pdf
coverletter: cover-letter.pdf
skillset: Skillset.pdf
social:
  - title: email
    url: mailto:swatitiwari04@gmail.com
  - title: twitter
    url: https://twitter.com/swati_tiwari
  - title: trailhead
    url: https://trailblazer.me/swatitiwarii
  - title: github
    url: https://github.com/swati-tiwari
  - title: linkedin
    url: https://www.linkedin.com/in/swatitiwari09
  - title: trailblazer
    url: https://www.linkedin.com/in/swatitiwari09

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
