# Site settings
name: Swati Tiwari
title: Swati Tiwari | Salesforce Developer & Consultant
description: Design-minded, detail oriented software engineer passionate about combining beautiful code for the clients.
url: https://brittanychiang.com/
baseurl: ""
email: swatitiwari04@gmail.com
cover: https://brittanychiang.com/v2/img/og.jpg
logo: https://brittanychiang.com/v2/img/logo-black.png
resume: https://brittanychiang.com/v2/resume.pdf
social:
  - title: Email
    url: mailto:swatitiwari04@gmail.com
  - title: X
    url: https://twitter.com/swati_tiwari
  - title: Trailhead
    url: https://trailblazer.me/swatitiwarii
  - title: Github
    url: https://github.com/swati-tiwari
  - title: Linkedin
    url: https://www.linkedin.com/in/swatitiwari09
  - title: Trailblazer
    url: https://www.linkedin.com/in/swatitiwari09

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
