# Site settings
name: Swati Tiwari
title: Swati Tiwari | Salesforce Developer & Consultant
description: Design-minded, detail oriented software engineer passionate about combining beautiful code for the clients.
url: https://swatitiwari.co.in/
baseurl: "https://swatitiwari.co.in"
email: swatitiwari04@gmail.com
cover: img/og.jpg
logo: /img/swati-tiwari-logo.jpg
resume: Resume.pdf
coverletter: cover-letter.pdf
skillset: Skillset.pdf
social:
  - title: email
    url: mailto:swatitiwari04@gmail.com
  - title: twitter
    url: https://twitter.com/swati_tiwarii
  - title: trailhead
    url: https://trailblazer.me/swatitiwarii
  - title: github
    url: https://github.com/swati-tiwari
  - title: linkedin
    url: https://www.linkedin.com/in/swatitiwari09
  - title: trailblazer
    url: https://toptrailblazers.com/u/swatitiwarii

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
